// Generated by CoffeeScript 1.7.1
(function() 
{
  $(document).ready(function() {
    var slideInterval, slideToNext, slideToPrev;
    var x=$("#alert_win li").nextAll().length;
    var y=$("#images li").nextAll().length;
    var overNine=true;
    
  if(x<8)
  {
            $("#top").hide();
          overNine=false;
  }
  else
  {
        if(y>8)
      {
              $("#top").show();
        
      }
      else
      {
        $("#top").hide();
              overNine=false;
      }
    
    }
  
    
    //定义轮播到下一页的方法
    slideToNext = function() {
      console.log(123)
      var slideCache;
      slideCache = $(".slide[role=1]");
      $("#images").append(slideCache);
      return $.each($(".slide"), function(i, li) {
        $(li).find(".overlay").remove();
        $(li).attr("role", i + 1);
        if (i !== 2) {
          return $(li).append("<div class='overlay'></div>");
        }
      });
    };
    
    //定义轮播到上一页的方法
    slideToPrev = function() {
      var slideCache, slideLength;
      slideLength = $(".slide").length;
      slideCache = $(".slide[role=" + slideLength + "]");
      $("#images").prepend(slideCache);
      return $.each($(".slide"), function(i, li) {
        $(li).find(".overlay").remove();
        $(li).attr("role", i + 1);
        if (i !== 2) {
          return $(li).append("<div class='overlay'></div>");
        }
      });
    };

    //设置定时器 3秒跳转一次
    slideInterval = window.setInterval(function() {
      return slideToNext();
    }, 2000);

    //定义点击向右的箭头
    $(".js-next").on("click", function() {
      return slideToNext();
    });

    //定义点击向左的箭头
    $(".js-prev").on("click", function() {
      return slideToPrev();
    });
  
  //大图的向左
    $("#light .leftO").click(function(){
    slideToPrev();
    $(".slide[role=3] img").click();
    
                      });
  
  
  //大图的向右
  $("#light .rightO").click(function(){
    slideToNext();
    $(".slide[role=3] img").click();
                      });
  
  
    //定义点击关闭按钮的事件
    $(".close-img").on("click", function() {
      $("#light .big-img").removeClass("rotate")
    if(!overNine)
    {
      $("#top").hide();
          $("#light").fadeOut();
          return slideInterval = window.setInterval(function() {
          return slideToNext();
          }, 2000);
    }
    else
    {
       $("#light").fadeOut();
           return slideInterval = window.setInterval(function() {
           return slideToNext();
           }, 2000);
    }
    });
    //定义点击图片的事件 
    return $(".small-img").on("click", function() {
      var src;
      src = $(this).find("img").attr("src");
      $("#light .big-img").addClass("rotate").css("-moz-transform", "rotate(360deg)").css("-moz-transition-duration", "0.4s")
      imgHref = $(this).find("img").attr("src");
      var status = false;
      while(!status){
           slideToNext()
      if($(".slide[role=3] img").attr("src") == imgHref)
      {
          status = true;
      }
    }
    if(!overNine)
    {
        <!--$("#top").show();-->
           $("#light").fadeIn().find(".big-img").attr("src", src);
            return clearInterval(slideInterval);
    }
    else
    {
      $("#light").fadeIn().find(".big-img").attr("src", src);
          return clearInterval(slideInterval);
    }
    });
  });

}).call(this);
